import { useEffect, useRef } from 'react'
import gsap from 'gsap'
import { usePresentation } from '../hooks/usePresentation'
import MagicCodeBlock from '../components/code/MagicCodeBlock'

const step0 = `// The N+1 Problem — before lazy loading
List<Order> orders = repository.findAll();   // 1 SQL

for (Order order : orders) {
    // Hibernate fires 1 SQL per order to load Customer
    System.out.println(order.getCustomer().getName());
}
// 1000 orders = 1001 database round-trips ⚠️`

const step1 = `@Entity
public class Order {

    @Id
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY) // Don't load yet
    private Customer customer;         // A proxy will live here
}`

const step2 = `Order order = repository.findById(1L);
// SQL: SELECT * FROM orders WHERE id = 1
// order.customer is a PROXY — no SQL for Customer yet

System.out.println(order.getId());
// Still no Customer SQL — getId() reads from Order

String name = order.getCustomer().getName();
// ⚡ NOW Hibernate fires: SELECT * FROM customers WHERE id = ?`

const step3 = `// ⚠️ Runtime-generated by ByteBuddy — never on disk
public class Customer$HibernateProxy extends Customer
    implements HibernateProxy {

    private LazyInitializer initializer;

    @Override
    public String getName() {
        // Every method call is intercepted here
        return (String) initializer.getImplementation().getName();
    }
}`

const step4 = `// AbstractLazyInitializer.java (Hibernate source)
public final Object getImplementation() {
    if (!initialized) {
        // First access: fire the SQL
        this.target = session.immediateLoad(entityName, id);
        this.initialized = true;
    }
    // All future calls skip the DB and use cached target
    return target;
}`

const CODE_STEPS = [step0, step1, step2, step3, step4]

const STEP_HIGHLIGHTS = [
  [3, 4, 5, 6],          // N+1: the loop lines with customer access
  [6, 7],          // Lazy mapping: @ManyToOne + private Customer
  [7, 8],          // Triggering: getCustomer().getName()
  [2, 7, 8, 9, 10, 6],   // Proxy class: extends + getImplementation call
  [2, 3, 4, 5, 8],    // Initializer: check + SQL + return
]

const STEP_CALLOUTS = [
  {
    tag: "N+1 Problem",
    text: "Without lazy loading, Hibernate eagerly fetches every related entity. 1000 orders = 1001 SQL queries.",
    color: "#C62828",
  },
  {
    tag: "Virtual Proxy Declared",
    text: "FetchType.LAZY tells Hibernate: don't load Customer yet. Create a proxy placeholder instead.",
    color: "#B8960C",
  },
  {
    tag: "The SQL Trigger",
    text: "order.getCustomer() returns the proxy. Only getName() — a non-ID method — causes SQL to fire.",
    color: "#B8960C",
  },
  {
    tag: "Runtime Subclass",
    text: "Hibernate generates a subclass of Customer that intercepts every method call via the LazyInitializer.",
    color: "#1565C0",
  },
  {
    tag: "Delegation Pattern",
    text: "getImplementation() checks initialized, fires SQL on first access, then returns the real target for all future calls.",
    color: "#2E7D32",
  },
]


function HibernateFlowSVG({ activeStep }) {
  const highlightApp = activeStep <= 2
  const highlightProxy = activeStep === 3 || activeStep === 4
  const highlightDB = activeStep === 4
  const highlightReal = activeStep === 4

  const activeOpacity = 1;
  const inactiveOpacity = 0.25;

  return (
    <svg width="100%" viewBox="0 0 400 180" preserveAspectRatio="xMidYMid meet" style={{ display: 'block', maxHeight: '100%', transition: 'all 0.4s ease' }}>
      <defs>
        <marker id="arrow-gold" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto">
          <polygon points="0 0, 8 3, 0 6" fill="#B8960C" />
        </marker>
        <marker id="arrow-red" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto">
          <polygon points="0 0, 8 3, 0 6" fill="#C62828" />
        </marker>
        <marker id="arrow-green" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto">
          <polygon points="0 0, 8 3, 0 6" fill="#2E7D32" />
        </marker>
      </defs>

      {/* 1. The Call */}
      <g opacity={highlightApp ? activeOpacity : inactiveOpacity} style={{ transition: 'opacity 0.4s' }}>
        <rect x="10" y="60" width="70" height="34" rx="6" fill="var(--surface)" stroke="var(--border)" strokeWidth="1" />
        <text x="45" y="81" textAnchor="middle" fontSize="10" fontWeight="700" fill="var(--text)">App Code</text>

        <path d="M80 77 L125 77" stroke="#B8960C" strokeWidth="1.5" markerEnd="url(#arrow-gold)" />
        <text x="102" y="70" textAnchor="middle" fontSize="8" fill="#B8960C" fontWeight="700">.getName()</text>
      </g>

      {/* 2. The Proxy (The Interceptor) */}
      <g opacity={highlightProxy ? activeOpacity : inactiveOpacity} style={{ transition: 'opacity 0.4s' }}>
        <rect x="135" y="40" width="100" height="74" rx="8" fill="rgba(184,150,12,0.05)" stroke="#B8960C" strokeWidth={highlightProxy ? 2 : 1} strokeDasharray="4 2" />
        <text x="185" y="58" textAnchor="middle" fontSize="10" fontWeight="800" fill="#B8960C">Customer$Proxy</text>
        <rect x="145" y="68" width="80" height="36" rx="4" fill="#FFFDE7" stroke="#B8960C" strokeWidth="1" />
        <text x="185" y="83" textAnchor="middle" fontSize="8" fontWeight="700" fill="#B8960C">Check Flag</text>
        <text x="185" y="94" textAnchor="middle" fontSize="7" fill="#B8960C">(initialized?)</text>
      </g>

      {/* 3. The Fetch (Branch) */}
      <g opacity={highlightDB ? activeOpacity : inactiveOpacity} style={{ transition: 'opacity 0.4s' }}>
        <path d="M185 114 L185 140" stroke="#C62828" strokeWidth="1.5" markerEnd="url(#arrow-red)" />
        <text x="190" y="130" fontSize="8" fill="#C62828" fontWeight="700">1. SQL</text>
        <rect x="145" y="145" width="80" height="24" rx="4" fill="#FFEBEE" stroke="#C62828" strokeWidth="1" />
        <text x="185" y="160" textAnchor="middle" fontSize="9" fontWeight="800" fill="#C62828">Session</text>
      </g>

      {/* 4. The Real Object */}
      <g opacity={highlightReal ? activeOpacity : inactiveOpacity} style={{ transition: 'opacity 0.4s' }}>
        <path d="M225 157 Q 340 157 340 114" fill="none" stroke="#2E7D32" strokeWidth="1.5" strokeDasharray="3 3" markerEnd="url(#arrow-green)" />
        <text x="282" y="166" textAnchor="middle" fontSize="8" fill="#2E7D32" fontWeight="700">2. Inflate</text>

        <rect x="290" y="40" width="100" height="74" rx="8" fill="#E8F5E9" stroke="#2E7D32" strokeWidth={highlightReal ? 2 : 1} />
        <text x="340" y="58" textAnchor="middle" fontSize="10" fontWeight="800" fill="#2E7D32">Real Object</text>
        <text x="340" y="85" textAnchor="middle" fontSize="18">👤</text>

        {/* 5. Delegation */}
        <path d="M235 77 L285 77" stroke="#2E7D32" strokeWidth="1.5" markerEnd="url(#arrow-green)" />
        <text x="260" y="70" textAnchor="middle" fontSize="8" fill="#2E7D32" fontWeight="700">3. Delegate</text>
      </g>
    </svg>
  )
}





function ContextCard({ isVisible }) {
  const ref = useRef(null)
  useEffect(() => {
    if (isVisible) {
      const ctx = gsap.context(() => {
        gsap.fromTo('.s07c-logo', { opacity: 0, y: -20 }, { opacity: 1, y: 0, duration: 0.45, ease: 'power3.out' })
        gsap.fromTo('.s07c-viz', { opacity: 0, scale: 0.9 }, { opacity: 1, scale: 1, duration: 0.6, delay: 0.3, ease: 'back.out(1.2)' })
        gsap.fromTo('.s07c-stat', { opacity: 0, x: 20 }, { opacity: 1, x: 0, duration: 0.4, stagger: 0.1, delay: 0.4, ease: 'power2.out' })
      }, ref)
      return () => ctx.revert()
    }
  }, [isVisible])

  return (
    <div ref={ref} style={{
      gridArea: 'stack',
      display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: 30, alignItems: 'center', overflow: 'hidden',
      opacity: isVisible ? 1 : 0,
      pointerEvents: isVisible ? 'auto' : 'none',
      visibility: isVisible ? 'visible' : 'hidden',
      transition: 'opacity 0.4s ease, visibility 0.4s ease'
    }}>


      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
        <div className="s07c-logo" style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
          <span style={{ fontSize: 50, lineHeight: 1 }}>🐘</span>
          <div>
            <h1 style={{ margin: 0, fontSize: 32, fontFamily: "'DM Sans',sans-serif", fontWeight: 800, color: 'var(--text)' }}>
              Hibernate ORM
            </h1>
            <p style={{ margin: '4px 0 0', color: 'var(--text-faint)', fontSize: 14 }}>
              The dynamic subclassing engine.
            </p>
          </div>
        </div>

        <div className="s07c-teaser callout-gold" style={{ fontSize: 15, padding: '16px 20px', lineHeight: 1.6 }}>
          Hibernate uses <strong>ByteBuddy</strong> to generate a hidden subclass of your entity at runtime.
          <br /><br />
          This "Ghost" object holds an ID but no data. It intercepts every method call to trigger a database fetch <em>only when needed</em>.
          <div style={{ marginTop: 12, display: 'flex', gap: 8 }}>
            <span className="badge">Lazy Loading</span>
            <span className="badge success">Proxy Pattern</span>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {[
            { icon: '👻', title: 'Hollow Proxy', desc: 'Initially contains only the primary key.' },
            { icon: '⚡', title: 'On-Demand SQL', desc: 'SQL fires only when a non-ID getter is called.' },
            { icon: '🚫', title: 'Detached Danger', desc: 'Closing the session too early leads to LazyInitializationException.' },
          ].map((s, i) => (
            <div key={i} className="s07c-stat" style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
              <span style={{ fontSize: 18 }}>{s.icon}</span>
              <div>
                <div style={{ fontWeight: 700, fontSize: 13, color: 'var(--text)' }}>{s.title}</div>
                <div style={{ fontSize: 12, color: 'var(--text-faint)' }}>{s.desc}</div>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="s07c-viz" style={{
        background: 'var(--surface)', border: '2px solid var(--border)',
        borderRadius: '24px', padding: '30px', position: 'relative',
        boxShadow: '0 20px 40px rgba(0,0,0,0.1)', height: '100%',
        display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center'
      }}>
        <div style={{ position: 'absolute', top: 20, left: 20, fontSize: 10, fontWeight: 800, color: 'var(--text-faint)', letterSpacing: 1 }}>THE GHOST SUBCLASS</div>

        <div style={{ width: '100%', textAlign: 'center' }}>
          <div style={{ fontSize: 40, marginBottom: 10, filter: 'grayscale(1) opacity(0.5)' }}>📦 Customer</div>
          <div style={{ fontSize: 24, color: 'var(--text-faint)' }}>↓ extends ↓</div>
          <div style={{
            marginTop: 15, padding: '20px', border: '2px dashed #B8960C', borderRadius: 16,
            background: 'rgba(184,150,12,0.05)', position: 'relative'
          }}>
            <div style={{ fontSize: 40, filter: 'drop-shadow(0 0 10px rgba(184,150,12,0.3))' }}>👻 Customer$Proxy</div>
            <div style={{ fontSize: 11, color: '#B8960C', fontWeight: 700, marginTop: 10 }}>RUNTIME GENERATED</div>
          </div>
        </div>

        <div style={{ marginTop: 30, fontSize: 12, color: 'var(--text-faint)', textAlign: 'center', fontStyle: 'italic' }}>
          "The application thinks it's a Customer,<br />but it's actually a ByteBuddy ghost."
        </div>

        <div style={{ marginTop: 'auto', paddingTop: 20 }}>
          <span style={{ fontSize: 12, color: 'var(--text-faint)' }}>
            Press <kbd style={{ background: 'var(--surface-faint)', border: '1px solid var(--border)', padding: '2px 6px', borderRadius: 4 }}>H</kbd> to see the code →
          </span>
        </div>
      </div>

    </div>
  )
}


function CodeView({ codeStep, isVisible }) {
  const ref = useRef(null)
  useEffect(() => {
    if (isVisible) {
      const ctx = gsap.context(() => {
        gsap.fromTo('.s07v-left', { opacity: 0, x: -18 }, { opacity: 1, x: 0, duration: 0.38, ease: 'power2.out' })
        gsap.fromTo('.s07v-right', { opacity: 0, x: 18 }, { opacity: 1, x: 0, duration: 0.38, delay: 0.1, ease: 'power2.out' })
      }, ref)
      return () => ctx.revert()
    }
  }, [isVisible])

  const filenames = [
    'PerformanceProblem.java',
    'Order.java',
    'Main.java',
    'Customer$HibernateProxy.java (conceptual — runtime-generated by ByteBuddy)',
    'AbstractLazyInitializer.java'
  ]

  const safeStepForData = Math.max(0, codeStep)
  const callout = STEP_CALLOUTS[safeStepForData] || STEP_CALLOUTS[0]
  const filename = filenames[safeStepForData]


  return (
    <div ref={ref} style={{
      gridArea: 'stack',
      display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24, minHeight: 0, alignItems: 'stretch',
      opacity: isVisible ? 1 : 0,
      pointerEvents: isVisible ? 'auto' : 'none',
      visibility: isVisible ? 'visible' : 'hidden',
      transition: 'opacity 0.4s ease, visibility 0.4s ease'
    }}>

      <div className="s07v-left" style={{ minHeight: 0, display: 'flex', flexDirection: 'column' }}>
        <MagicCodeBlock
          codeSteps={CODE_STEPS}
          activeStep={codeStep}
          stepHighlights={STEP_HIGHLIGHTS}
          lang="java"
          height="100%"
          filename={filename}
          permanentHighlights={true}
        />
      </div>
      <div className="s07v-right" style={{
        display: 'flex', flexDirection: 'column', overflow: 'hidden',
        background: 'var(--surface)', border: '1px solid var(--border)',
        borderRadius: 'var(--radius)', padding: '14px 16px',
        boxShadow: 'var(--shadow)', gap: 10,
      }}>
        <p style={{ flexShrink: 0, fontSize: 10, color: 'var(--text-faint)', textTransform: 'uppercase', letterSpacing: '1px', fontFamily: "'JetBrains Mono',monospace", margin: 0 }}>
          The Lazy Loading Lifecycle
        </p>
        <div style={{ flex: 1, overflow: 'hidden', display: 'flex', alignItems: 'center' }}>
          <HibernateFlowSVG activeStep={safeStepForData} />
        </div>

        <div className="callout-gold" style={{ flexShrink: 0, fontSize: 11, padding: '10px 14px', textAlign: 'left', lineHeight: 1.5, borderColor: callout.color }}>
          <strong>{callout.tag}:</strong> {callout.text}
        </div>
      </div>
    </div>
  )
}



export default function Slide07Hibernate() {
  const { highlightStep } = usePresentation()
  const isCodeView = highlightStep >= 1
  const codeStep = (highlightStep - 1) % CODE_STEPS.length

  return (
    <div className="slide-shell">
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
        <h2 className="slide-title" style={{ marginBottom: 0 }}>
          {isCodeView ? 'JPA / Hibernate — Lazy Proxy' : 'OSS Example: Hibernate ORM'}
        </h2>
        <span className="badge">Java</span>
        {isCodeView && <span className="badge success">Virtual Proxy</span>}
        {isCodeView && (
          <span style={{ marginLeft: 'auto', fontSize: 11, color: 'var(--text-faint)', fontFamily: "'JetBrains Mono',monospace", border: '1px solid var(--border)', padding: '2px 8px', borderRadius: 4 }}>
            hibernate-core · ByteBuddyProxyFactory.java
          </span>
        )}
      </div>
      <p className="slide-subtitle" style={{ marginBottom: 8 }}>
        {isCodeView
          ? <>Step {codeStep + 1} of {CODE_STEPS.length} · Usage and Implementation</>
          : 'A Virtual Proxy used by nearly every Enterprise Java application.'}
      </p>

      <div style={{ flex: 1, minHeight: 0, display: 'grid', gridTemplateAreas: "'stack'", gridTemplateRows: '1fr', gridTemplateColumns: '1fr' }}>
        <ContextCard isVisible={!isCodeView} />
        <CodeView codeStep={codeStep} isVisible={isCodeView} />
      </div>


      <div className="bottom-rule" />
    </div>
  )
}
