import { usePresentation } from '../hooks/usePresentation'

const NOTES = {
  1: `Good morning everyone — I'm Alex, welcome. In the next 25 minutes I want to take you through one of the most underrated patterns in software design: the Proxy. And underrated in a specific way — developers use it every single day without knowing they're doing it. By the end, you'll be able to name it, draw it, read it in a real codebase, and explain it to someone else. We're going from a simple problem you've almost certainly hit yourself all the way through to three production libraries starred on GitHub by tens of thousands of engineers: Spring Boot, OkHttp, Vue.js. Real code, not toys. I'll leave five minutes at the end for questions — shout out at any point if something's not clicking.`,

  2: `Here's the scenario. You're building a photo gallery — up to 12 images. The obvious implementation: load all 12 at startup. The terminal shows the result: 8,400 milliseconds. That's 8.4 seconds of white screen before the user sees anything. On mobile, on a slow connection, the user already closed the tab. My question for you — think about it for a second, don't just reach for the answer — why are we loading 12 images when a typical user might scroll through 2 or 3? [Pause.] Right. Most of you are already thinking 'load on demand'. That instinct is exactly correct. And what you just described has a name: the Proxy Pattern. We'll define it properly now, but you've already invented it.`,

  3: `Before any code, I want to build the mental model. A Proxy is a smart middleman — a wrapper that sits in front of an object and controls access to it. The word 'controls' is the key word for the entire pattern. Three classic flavors: a Protection Proxy controls WHO — like a security guard at a building entrance. A Lazy or Caching Proxy controls WHEN — expensive operations are deferred or remembered. A Remote Proxy represents a distant object locally — your ATM is a proxy to your bank account server. Keep asking throughout this talk: what is the proxy controlling? That question is your compass.`,

  4: `Let's ground this in structure — and I want to build this diagram together. Three participants. First: the Subject interface. This is the contract both the real object and the proxy must honor. One method: request(). Now RealSubject — the expensive or sensitive thing we're protecting. It implements Subject. Here's the critical insight: the Proxy also implements Subject. Same interface. So when the Client calls request(), it has no idea whether it's talking to the real thing or the proxy. That's not a side effect of the pattern — it IS the pattern. The Client is typed to the interface: Subject s = new ImageProxy('photo.jpg'). When s.display() is called, the proxy decides what happens. Does it create the real object? Check a cache? Verify a role? That decision logic lives entirely inside the proxy.`,

  5: `Let's trace through the code left to right. The interface: Image with one method, display(). RealImage implements it — notice the constructor calls loadFromDisk() immediately. Every time you new up a RealImage, you pay that cost up front. Now look at ImageProxy. Also implements Image — same interface. The constructor just stores the filename. No disk I/O. The field realImage starts as null. Then the magic in display(): if realImage is null, we haven't loaded yet, so we create it now — on demand. The null check IS the lazy loading. That's all it is. The same mechanism Spring uses for lazy beans, Hibernate for lazy-loaded relationships, every framework calls at startup. Look at the diagram: 8,400ms versus 120ms. The only code that changed is one proxy class.`,

  6: `Now the Protection Proxy — same structure, different purpose. Instead of deferring creation, we're gatekeeping access. The SecureDocumentProxy has a role field set at construction time: ADMIN, EDITOR, or GUEST. When read() is called, the proxy checks first. GUEST? SecurityException, never gets through. Authorised? Passes through, but also calls auditLog() — transparently logging the access. The RealDocument class has no idea about roles or logging. It just returns content. All that control logic lives in the proxy. The diagram shows three callers, one proxy, two paths. The authorised path reaches the real document. The unauthorised path ends at a SecurityException — the real document is never reached. Remember that: the proxy can say no. We'll come back to this when we talk about Decorators.`,

  7: `This is my favourite slide because it's the moment the pattern stops being academic. If you've ever written a Spring Boot application — and most of you have or will — you've almost certainly written @Cacheable. Did you know it generates a proxy class at runtime? Spring's AOP looks at your WeatherService and says: this method has @Cacheable. I'm going to wrap it in a generated class called WeatherService$SpringProxy. That generated class looks exactly like our ImageProxy — the same null-check pattern, the same structure. The annotation is syntactic sugar over the proxy. Look at the generated code: checks the cache, if hit returns early, if miss calls through and stores the result. Identical to our toy example. The GitHub link there — ProxyFactory.java in spring-projects/spring-framework — is worth reading. Millions of Spring applications rely on this.`,

  8: `OkHttp takes the Proxy pattern and puts it in a chain. Instead of one proxy wrapping one real object, you have a sequence of proxies, each wrapping the next. The Interceptor interface defines one method: intercept(Chain chain). Look at AuthInterceptor: receives a Chain, pulls the Request off it, builds a new one with an Authorization header, then calls chain.proceed() with the modified request. chain.proceed() doesn't call the server — it calls the next interceptor. The diagram shows the full flow: Auth, then Logging, then Cache. Only if Cache has no stored response does the request reach the network. [Raise hands] How many of you have used Axios? Axios interceptors — identical pattern. Django middleware? Same. Express middleware? Same. Different names, one pattern.`,

  9: `Something that might surprise you: JavaScript has a Proxy built into the language. First-class, in every browser since 2015. You write new Proxy(target, handler) and the handler defines 'traps' — functions intercepting operations on the target. A set trap fires when anyone writes a property. Look at the set trap: logs the write, then calls scheduleUpdate(). That call triggers Vue to re-render your component. That's Vue 3's entire reactivity system. Every time you call ref() or reactive(), the object you get back is wrapped in exactly this Proxy. Any write fires the set trap, Vue's scheduler sees it, your component updates. Without the proxy, Vue has no way to know state changed. MobX uses the same mechanism. One pattern, server-side with Spring, client-side with Vue.`,

  10: `Now let's categorize the four most common types of Proxy you'll see in production. First, the Virtual Proxy (the lazy-loader) — it's a stand-in for expensive objects like high-res images or database connections, only creating them when truly needed. Second, the Remote Proxy — think of this as the "diplomat". It lives in your local process but represents an object on a different machine, handling all the messy networking and serialization details. Third, the Protection Proxy (the gatekeeper) — it checks roles and permissions before allowing a call to reach the real object. And fourth, the Caching Proxy — it stores results of expensive operations so that repeated calls with the same arguments are served instantly. Look at the icons pop on the screen — each one represents a specific way the Proxy pattern provides control over your system.`,

  11: `So let's land this. Five triggers for reaching for the Proxy: lazy creation of expensive objects, access control and permissions, transparent caching, audit logging, and remote object representation. And critically — you've already been using it. Spring @Cacheable, OkHttp interceptors, Vue reactivity. Not advanced topics — your day-to-day tools. You've been writing Proxy patterns this whole time. The homework is simple: tonight, look at one of the three GitHub repositories linked below. Spring ProxyFactory.java, OkHttp RealInterceptorChain.java, or Vue's reactive.ts. Read the first 50 lines. You'll recognise everything. That is the measure of whether a pattern has clicked — not whether you can define it, but whether you can read production code and name what you're looking at. Any questions?`,
}

export default function PresenterNotes() {
  const { currentSlide, notesVisible } = usePresentation()
  return (
    <div id="presenter-notes" className={notesVisible ? 'visible' : ''}>
      <div className="notes-label">Presenter Notes — Slide {currentSlide}</div>
      {NOTES[currentSlide]}
    </div>
  )
}
